<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputPath>build\addons\counterstrikesharp\plugins\VIP_Gifts\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" />
  </ItemGroup>
 

</Project>
