<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Ссылка на VipCoreApi.dll (два уровня вверх → папка VIPCore) -->
    <Reference Include="RanksApi.dll">
      <HintPath>..\RanksApi.dll</HintPath>
    </Reference>
    <!-- Ссылка на VipCoreApi.dll (два уровня вверх → папка VIPCore) -->
    <Reference Include="VipCoreApi">
      <HintPath>..\..\VipCoreApi.dll</HintPath>
    </Reference>
    <!-- Ссылка на RanksApi.dll (предполагается, что лежит там же) -->
    <Reference Include="RanksApi">
      <HintPath>..\..\RanksApi.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
